language: java
matrix:
  include:
    - jdk: openjdk8
    - jdk: oraclejdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk12
    - jdk: oraclejdk12
env:
  global:
  - secure: hiAE0Gt7pcTmcQ/rjfK+KB+Mj1O3LaEM6wNgFleG04fuPbsUgTpF3U1HMTfEvU8nB0AEoIHgPZ2qWHIqGdJ23HfC7pTXtZXy8YSMOnPpTx8j9+qX0i7kJsqA6CNd+5i1CN0aM0uSd2CXRj7CFpwBa+5kfQmsml90oG3mev1MXcs=
  - # ^^SONATYPE_USERNAME
  - secure: Sa7tSlz29eOhOazmyGAfv7tFtaZjI1PMtgQJ3fFFZ2EVaAbxxGU/l+TVmcCOxOt7OdCf1MTgB9/dRGPZAuVdtelPIytoJEpB7U2qBci72K1at2zqKF6dq0pPswuwdbkqJeAf39M3J1nZcXKXwirU/J4OfwWyi5qwXpM8pO7W/qM=
  - # ^^SONATYPE_PASSWORD
  - GPG_KEY_NAME=C546418B
  - secure: BJo5bbJrlxg0v0JKFpNE3JP0cRmDclG4CwMJO+j+puHVwl1p/crgbq1mL3//DJ1USIWiIy98U+xQSH1/gIhAssPXUwI5Xv94AKgE7K/8hY1E7pqt6WSr9jGEMalceggFHHTNkfRXlet+Cpag7R73Fyx8++pEqMESpf043hc0EBc=
  - # ^^GPG_PASSPHRASE
cache:
  directories:
  - $HOME/.m2
after_success:
  - ./travis/code_cov.sh
before_deploy:
  - ./travis/before-deploy.sh
  - cp ./travis/.m2.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  skip_cleanup: true
  script: "if [ '${TRAVIS_JDK_VERSION}' = 'oraclejdk12' ]; then mvn deploy -P release -DskipTests=true ; fi"
  on:
    repo: thelinmichael/spotify-web-api-java
    branch:
    - master
    - v1
    tags: true
notifications:
  email:
    on_success: never
    on_failure: change
